version: '3.8'

services:

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todolist

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql